---
title: "Flood Catastrophe Reinsurance & Capital Optimisation"
subtitle: "Gulf Coast reference portfolio (FL, TX, LA, MS, AL), 2025 exposure: what to buy, what it costs, what it removes"
date: "{{today}}"
format:
  typst:
    papersize: a4
    margin:
      x: 2cm
      y: 1.8cm
    fontsize: 9.5pt
    section-numbering: "1."
---

*Generated by `make report` from `outputs/` (git `{{git_hash}}`). All money in USD, 2025 exposure basis. Prices are indicative technical premiums, not market quotes. Economic capital (EC) is a 99.5% one-year proxy for this portfolio's insurance risk, not a Solvency II SCR.*

# Executive summary

**What to buy.** {{recommended_desc}}. In the base model it reduces the 99.5% one-year economic capital proxy from USD {{gross_ec:,.0f}}m to USD {{ec_net:,.0f}}m, a capital relief of **{{relief_pct:.1%}}**, for an expected net cost of **USD {{net_cost:,.0f}}m a year** (premium USD {{premium:,.0f}}m less expected recoveries of USD {{exp_recovery:,.0f}}m). That is an implied cost of capital of **{{implied_coc:.1%}}**, {{coc_vs_hurdle}} the {{hurdle:.0%}} hurdle assumed for the insurer's own capital.

**Why.** The programme sits on the cost–capital frontier of {{n_programmes}} candidate programmes and is the Balanced choice at a {{hurdle:.0%}} hurdle: every additional step of protection up to it releases capital at a marginal cost below the hurdle, and {{next_step_sentence}}. Equivalently, it minimises the total cost of risk (net reinsurance cost + {{hurdle:.0%}} × net EC): USD {{tcr_rec:,.0f}}m against USD {{tcr_gross:,.0f}}m with no reinsurance and USD {{tcr_budget:,.0f}}m for the cheapest programme that releases at least {{budget_min_relief:.0%}} of capital.

**How much to trust it.** {{stress_sentence}} Two things drive the result and deserve management's attention. First, the reinsurer's diversification: with none (d = 1), reinsurance capital costs more than equity and the same rule picks {{d10_balanced_desc}}. Second, the tail rests on few events: without {{eo_event}} gross EC falls by {{eo_ec_drop:.0%}}, and the year bootstrap gives a 90% interval of {{relief_pct_p05:.0%}}–{{relief_pct_p95:.0%}} for capital relief.

**Affordability.** The recommended programme's premium is {{premium_share_of_portfolio:.0%}} of the portfolio's own premium (USD {{portfolio_premium_m:,.0f}}m). This is large because, at a {{hurdle:.0%}} hurdle, holding the gross capital would cost USD {{tcr_gross:,.0f}}m a year, more than the portfolio's expected margin before expenses (USD {{expected_margin:,.0f}}m). If that premium is not affordable, the Budget-first programme ({{budget_first_desc}}) releases {{budget_relief_pct:.0%}} of capital for USD {{budget_net_cost:,.0f}}m a year.

{{tbl_choices}}

# Portfolio and catastrophe model

**Portfolio.** NFIP policies in force in the five Gulf states, written in 2025: {{portfolio_policies:,.0f}} insured units, USD {{portfolio_tiv_bn:,.0f}}bn total insured value ({{fl_tiv_share:.0%}} in Florida) and USD {{portfolio_premium_m:,.0f}}m premium. It is a stylised reference portfolio built from NFIP data, not a model of the NFIP's finances. National totals from the same extract ({{national_policies_2025:,.0f}} insured units, USD {{national_tiv_2025_tn:.2f}}tn) match the order of magnitude published by the Congressional Research Service.

**Events.** Claims ({{claims_rows:,}} in 2009–2025) are grouped by FEMA's `floodEvent` label and each event is restated to 2025 exposure by the ratio of state written insured value in 2025 to the event year (no CPI, which would double count value growth). Events of at least USD {{u0:,.0f}}m as-if form the catalogue: {{n_events_calib}} events in {{calibration_start}}–{{calibration_end}} totalling USD {{calib_event_total_bn:,.1f}}bn; everything else is attritional (mean USD {{attritional_mean:,.0f}}m a year). In the active years one event supplied most of the year's loss, the signature of accumulation risk.

{{tbl_events}}

**Loss model.** Annual loss = attritional + sum of event losses. Frequency is {{frequency_family}} with {{frequency_mean:.2f}} events a year (dispersion index {{dispersion:.2f}}; likelihood-ratio statistic {{lr_stat:.2f}}, far below the {{lr_critical}} needed for a negative binomial). Severity is a {{severity_family}} fitted by maximum likelihood with left truncation at USD {{u0:,.0f}}m, chosen by AIC among lognormal, log-logistic and Burr XII after checking that each of the five largest events is unremarkable under the fit. The three fits are within {{aic_spread:.1f}} AIC points of each other; with only {{n_events_calib}} events, generalised Pareto tail estimates were unstable, so GPD is used only as a stress. Each simulated event is capped at {{cap_multiple:.0f}}× the largest calibration event (USD {{cap:,.0f}}m). Attritional loss is bootstrapped from the calibration years.

**Simulation.** {{n_sims:,}} years (seed {{seed}}); VaR 99.5 moves by {{conv_diff:.2%}} at {{conv_years:,}} years. Gross mean loss USD {{gross_mean:,.0f}}m, 1-in-200 annual loss USD {{gross_var_995:,.0f}}m, EC USD {{gross_ec:,.0f}}m. {{cap_sentence}} The tail beyond the largest observed event therefore comes from the fitted shape and the cap, not from data.

{{tbl_ep}}

![Gross OEP and AEP with the calibration years](_figures/hero_1_ep_curves.png){width=62%}

# Reinsurance structure and pricing

**Contracts.** Quota share ({{qs_shares}}) inures to catastrophe excess of loss, which responds per event to the retained event loss. Layers are designed in return-period terms: attachment at the 1-in-{{attach_rps}} event loss, exhaustion at 1-in-{{exhaust_rps}}, as single layers or two-layer towers split at {{split_rps}}, placed {{placements}}, with zero or one reinstatement at {{reinst_rate:.0%}}. The grid has {{n_grid_ids}} programme IDs and {{n_programmes}} distinct dollar contracts{{dedupe_reason}}.

**Pricing.** Each layer's indicative technical premium covers its modelled expected loss (EL), a {{coc_r:.0%}} cost of capital on {{d:.1f}} × the reinsurer's standalone capital (TVaR 99.5 minus EL), and a {{xol_expense:.0%}} expense load; expected reinstatement premium is part of the reinsurer's income, so the upfront premium is reduced accordingly. The quota share is priced on the same principles with a {{qs_expense:.0%}} expense load. The factor d stands for the reinsurer's diversification: in a global book the layer's marginal capital is far below its standalone capital, and without that no reinsurance could ever be cheaper than the insurer's own capital. Historical burning cost is shown beside modelled EL: the {{bc_layer}} layer was hit in {{bc_years_hit}} of the {{n_calib_years}} calibration years and burned USD {{bc_value:,.0f}}m a year against a modelled EL of USD {{bc_el:,.0f}}m, a reminder that the fitted tail is not conservative.

**Recommended programme.**

{{tbl_layers}}

![Gross vs net AEP for the recommended programme](_figures/hero_2_gross_net.png){width=62%}

# Capital and programme decision

For every programme, net annual loss = gross loss − recoveries + premiums + reinstatement premiums. A fixed premium raises both VaR and the mean, so it does not change EC; capital relief comes from recoveries in the tail. Net cost = premiums + expected reinstatement premiums − expected recoveries, the price of transferring the risk; implied cost of capital = net cost ÷ capital relief.

Across all programmes the implied cost of capital lies between {{coc_min:.1%}} and {{coc_max:.1%}}, all below the {{hurdle:.0%}} hurdle, because the reinsurer charges about {{coc_r_d:.0%}} on capital plus expenses. {{n_frontier}} programmes are efficient (no other programme is both cheaper and needs less capital). Walking up the lower convex hull of the frontier from no reinsurance, each step's marginal cost of capital is:

{{tbl_hull}}

![Cost–capital frontier](_figures/hero_3_frontier.png){width=68%}

The Balanced rule stops before the first step whose marginal cost exceeds the hurdle. At {{h_lo:.0%}} it picks `{{balanced_08_id}}`; at {{h_hi:.0%}}, `{{balanced_12_id}}`. There is no single optimum: the choice depends on the budget, the risk appetite and the cost of the insurer's own capital, which is why the frontier and the three choices are shown together.

# Validation, sensitivities and market benchmark

**Convergence.** The recommended programme's capital relief moves by {{conv_rec_diff:.2%}} at {{conv_years:,}} years.

**Temporal holdout.** Refitted on {{fit0}}–{{fit1}}, the model expected {{ho_count_mean:.1f}} events in {{test0}}–{{test1}}; {{ho_count_obs}} occurred (percentile {{ho_count_pct:.0%}}). Hurricane Ian was a 1-in-{{ho_ian_rp:.0f}} event under that model. The five-year window can reveal a model that is badly off, not confirm a 1-in-200 tail.

**Largest event removed.** Without {{eo_event}}, gross EC falls to USD {{eo_gross_ec:,.0f}}m (−{{eo_ec_drop:.0%}}) and the Balanced choice becomes {{eo_balanced_desc}}; the recommended contract still releases {{eo_rec_relief_pct:.0%}} of the smaller capital at {{eo_rec_coc:.1%}}.

**Parameter uncertainty.** Resampling the {{n_calib_years}} calibration years ({{n_boot}} replicates) gives 90% intervals of USD {{gross_ec_p05:,.0f}}m–{{gross_ec_p95:,.0f}}m for gross EC, {{relief_pct_p05:.0%}}–{{relief_pct_p95:.0%}} for the recommended programme's relief and {{implied_coc_p05:.1%}}–{{implied_coc_p95:.1%}} for its implied cost of capital.

**Stresses and sensitivities** (the contract grid is fixed in dollars; each scenario re-prices it and re-applies the Balanced rule):

{{tbl_stress}}

**Market benchmark.** Compared by attachment probability ({{band_ap_lo:.0%}}–{{band_ap_hi:.0%}}), technical rates on line of {{band_rol_min:.1%}}–{{band_rol_max:.1%}} are below FEMA's traditional NFIP placements ({{fema_rol_2023:.1%}}, {{fema_rol_2024:.1%}} and {{fema_rol_2025:.1%}} in {{fema_y0}}–{{fema_y1}}), largely because the model's layers are wide (low expected loss per unit of limit), while FloodSmart Re's tranches are thin. Price multiples of expected loss ({{band_mult_min:.1f}}–{{band_mult_max:.1f}}×) are comparable with FloodSmart Re cat bond spreads over expected loss ({{cb_mult_min:.1f}}–{{cb_mult_max:.1f}}×). FEMA buys far less protection, attaching at USD {{fema_attach_bn:.0f}}bn nationally with {{fema_share_lo:.0%}}–{{fema_share_hi:.0%}} shares, under a public budget rather than a cost-of-capital objective. The benchmarks cover the national NFIP (all floods for FEMA's tower, named storms only for FloodSmart Re) and support only this order-of-magnitude comparison; the model was not adjusted towards them.

# Limitations

- Historical-event model, not a vendor catastrophe model: no hazard, hydraulics or vulnerability modules.
- {{n_calib_years}} calibration years: the 1-in-200 tail rests on the severity family and the event cap, with wide parameter uncertainty. Pre-2009 events (Katrina, Ike) are excluded for lack of consistent exposure data.
- As-if restatement adjusts only for state-level insured value: no within-state geography, building standards, mitigation or Risk Rating 2.0 mix changes.
- {{holdout0}}–{{holdout1}} are held out of calibration ({{holdout0}} is immature); open events are not developed.
- Events are FEMA `floodEvent` labels, not a treaty hours clause; several span more than a week.
- Attritional losses are assumed independent of catastrophe events; paid claims exclude loss adjustment expense.
- Prices are indicative technical premiums with assumed cost of capital, diversification and expenses; they are not market quotes, and the recommendation depends on the diversification assumption.
- Economic capital is an internal 99.5% one-year proxy for this portfolio's insurance risk only (no reinsurer default, market or operational risk); it is not a Solvency II SCR.
- The portfolio is stylised; market benchmarks support only order-of-magnitude comparison.

*Data: OpenFEMA NFIP Redacted Claims and NFIP Redacted Policies. This product uses the FEMA OpenFEMA API, but is not endorsed by FEMA. The Federal Government or FEMA cannot vouch for the data or analyses derived from these data after the data have been retrieved from the Agency's website(s). The Gulf Coast portfolio is a stylised insurance portfolio calibrated to the exposure and claims experience observed in the NFIP Gulf states; it is not intended to reproduce the finances of the NFIP itself. Reinsurance prices are indicative technical premiums, not market quotes. Economic capital is a 99.5% one-year proxy, not a Solvency II SCR.*
