"""M2 step: write the event catalogue, attritional series, top-events table and reports/events.md."""
from __future__ import annotations

import pandas as pd

from floodcat.events import catalogue
from floodcat.events.asif import asif_factors
from floodcat.utils.io import PROCESSED_DIR, REPORTS_DIR, TABLES_DIR, load_config


def _fmt(x, d=1):
    return f"{x:,.{d}f}"


def run() -> None:
    port = load_config("portfolio")
    mod = load_config("modelling")
    claims = pd.read_parquet(PROCESSED_DIR / "claims_clean.parquet")
    exposure = pd.read_parquet(PROCESSED_DIR / "exposure_by_state_year.parquet")
    events, att, asg = catalogue.build(claims, exposure)

    events.to_parquet(PROCESSED_DIR / "event_catalogue.parquet", index=False)
    att.to_parquet(PROCESSED_DIR / "attritional_by_year.parquet", index=False)
    asg[["id", "state", "t", "flood_event", "bucket", "loss_nominal", "loss_asif"]].to_parquet(PROCESSED_DIR / "claim_assignment.parquet", index=False)

    top = events.sort_values("loss_asif", ascending=False).head(10)
    top[["event_id", "name", "year", "period", "n_claims", "loss_nominal", "loss_cpi", "loss_asif"]].round(1).to_csv(TABLES_DIR / "top_events.csv", index=False)

    u0 = mod["event_threshold_u0"]
    u0s = mod["event_threshold_sensitivity"]
    cal = events[events["period"] == "calibration"]
    n_inc = int(cal["included"].sum())
    n_inc_s = int((cal["loss_asif"] >= u0s).sum())
    print(f"events: {len(events)} labels, {n_inc} included in calibration at u0={u0}", flush=True)

    # sorted list for the u0 decision
    srt = events.sort_values("loss_asif", ascending=False)
    rows = [f"| {i + 1} | {r.name} | {r.year} | {r.period} | {_fmt(r.loss_nominal)} | {_fmt(r.loss_asif)} | {'yes' if r.included else ''} |"
            for i, r in enumerate(srt.itertuples())]

    # share of each calibration/holdout year's as-if loss from its largest event
    tot = asg.groupby("t")["loss_asif"].sum()
    big = events.groupby("year")["loss_asif"].max()
    yr = pd.DataFrame({"total_asif": tot, "largest_event_asif": big}).fillna(0.0)
    yr["share"] = yr["largest_event_asif"] / yr["total_asif"]
    yr_rows = [f"| {y} | {_fmt(r.total_asif)} | {_fmt(r.largest_event_asif)} | {r.share:.0%} |" for y, r in yr.iterrows()]

    f = asif_factors(exposure, port["target_year"]).pivot(index="year", columns="state", values="factor")
    f_rows = [f"| {y} | " + " | ".join(f"{f.loc[y, s]:.3f}" for s in port["states"]) + " |" for y in f.index]

    long = events[events["span_days"] > 7]
    long_rows = [f"| {r.name} | {r.year} | {r.first_date:%Y-%m-%d} | {r.last_date:%Y-%m-%d} | {r.span_days} | {_fmt(r.loss_asif)} |" for r in long.itertuples()]

    top_rows = [f"| {r.name} | {r.year} | {r.period} | {r.n_claims:,} | {_fmt(r.loss_nominal)} | {_fmt(r.loss_cpi)} | {_fmt(r.loss_asif)} |" for r in top.itertuples()]

    cal_att = att[att["period"] == "calibration"]
    cal_ev_total = cal.loc[cal["included"], "loss_asif"].sum()
    text = f"""# Event catalogue and as-if restatement (M2)

Generated by `make events`. USD m. As-if = restated to {port['target_year']} written TIV by state (SPEC §6.2); CPI-only is a sensitivity column.

## Summary

- `floodEvent` labels with claims in the five states, {port['history_years'][0]}–{port['history_years'][1]}: {len(events)}.
- Calibration period {port['calibration']['start']}–{port['calibration']['end']}: {len(cal)} labels, **{n_inc} included** at u₀ = USD {u0:,}m (at the USD {u0s:,}m sensitivity: {n_inc_s}).
- Calibration as-if totals: included events USD {_fmt(cal_ev_total)}m, attritional USD {_fmt(cal_att['a_asif'].sum())}m over {len(cal_att)} years (mean A_t USD {_fmt(cal_att['a_asif'].mean())}m).

## As-if factors TIV[s, {port['target_year']}] / TIV[s, t]

| Year | {' | '.join(port['states'])} |
|---|{'---|' * len(port['states'])}
{chr(10).join(f_rows)}

## Top 10 events by as-if loss

| Event | Year | Period | Claims | Nominal | CPI-only | As-if |
|---|---|---|---|---|---|---|
{chr(10).join(top_rows)}

## Share of each year's as-if loss from its largest event

| Year | Total as-if | Largest event | Share |
|---|---|---|---|
{chr(10).join(yr_rows)}

## Events spanning more than 7 days (hours-clause discussion; not split)

| Event | Year | First loss | Last loss | Span (days) | As-if |
|---|---|---|---|---|---|
{chr(10).join(long_rows)}

## All events, sorted by as-if loss (u₀ decision)

| # | Event | Year | Period | Nominal | As-if | Included |
|---|---|---|---|---|---|---|
{chr(10).join(rows)}
"""
    (REPORTS_DIR / "events.md").write_text(text)
